import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export function Visionpro(props) {
  const { nodes, materials } = useGLTF('/apple_vision_pro_ios16.glb');
  // added rotation
  const groupRef = useRef();

  useFrame(() => {
    groupRef.current.rotation.y += 0.01; // Adjust the rotation speed as needed
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NCTuWVhPfXbauhX.geometry}
          material={materials.cfENkBJbuidhJQR}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MNXHJkKVjmbUNKU.geometry}
          material={materials.oTqiLbrwcjsRgMt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dbHbxcqmrAncXcC.geometry}
          material={materials.VphdCyWbkVqOTZM}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RMjnjXyMgoTxvNO.geometry}
          material={materials.vooHjZuayuJGiMQ}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PmnjxmiXJTgjNWb.geometry}
          material={materials.qDOcIjVpElQVnfu}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.maRjJfyAOWUFfqI.geometry}
          material={materials.ZOxfklNhssATaVX}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.yHomCHSOPycwYvw.geometry}
          material={materials.MQCEVrylLIUQrVK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ZpISlXViQsOjnoI.geometry}
          material={materials.AAfeebOMlIFREnV}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.nSxxllOTLoQHyQZ.geometry}
          material={materials.AAfeebOMlIFREnV}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RfUlkBWLMcnnjDZ.geometry}
          material={materials.euiQmuWDHAWaTrM}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QJrVTzJCWMTTMlr.geometry}
          material={materials.WSSwRvibmqaLYZi}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.iSAWOSRcnEglMgD.geometry}
          material={materials.qJCgguKxFcHIxWa}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cZcyOzYlhNSplIL.geometry}
          material={materials.YfKnpdtpUYsluRm}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.EbmJgvvXipWjEMi.geometry}
          material={materials.BCKXYWKgOWAMzzp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.xoJVrtkFfggFByx.geometry}
          material={materials.XKlUGvPEIYYLEPM}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NMVTgvZNMHRVFee.geometry}
          material={materials.ucekphvVRyoLWgE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.UDHdONgBtzYRwyk.geometry}
          material={materials.jOkVLpNIDGFLUJe}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.KCuSLrGBXunxbKi.geometry}
          material={materials.ucekphvVRyoLWgE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.OuafqOjNBHbOxeM.geometry}
          material={materials.BCKXYWKgOWAMzzp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.onCnMAgiUfYghCa.geometry}
          material={materials.eFnCMDGzSpQJEdf}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DRUMenkquqOqPBB.geometry}
          material={materials.schaJKIVUmSWLQA}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fYsQHZAKKxrBUHu.geometry}
          material={materials.uhSjoqjjxLxIJEp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bRkfhfzPFhAcloN.geometry}
          material={materials.xjMjLzeClXxPZiL}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.iQvheLuzdQkuSeJ.geometry}
          material={materials.aAXWAJGJAtUuAVC}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.puLESYTHooXoUCA.geometry}
          material={materials.pqksKtWbSqRTkqv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XHIStvRRJuEGVeQ.geometry}
          material={materials.uhSjoqjjxLxIJEp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SxaGKaPygGiLcmN.geometry}
          material={materials.movFhSaNkSrNKyM}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.qKXRmmKkymmLTYt.geometry}
          material={materials.aAXWAJGJAtUuAVC}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bJCbNxhrcmEdcCM.geometry}
          material={materials.cgOiivtAxUoeEfW}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BAxMEALGGWqitaP.geometry}
          material={materials.aAXWAJGJAtUuAVC}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HNXdaurOJgVpqwO.geometry}
          material={materials.uhSjoqjjxLxIJEp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cLqNTiqGrfBAsrs.geometry}
          material={materials.movFhSaNkSrNKyM}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wFzJvNXcWBRHhdQ.geometry}
          material={materials.xjMjLzeClXxPZiL}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DAQxQnEgVbUVChn.geometry}
          material={materials.aAXWAJGJAtUuAVC}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.EnVjHvEbvGptqIc.geometry}
          material={materials.pqksKtWbSqRTkqv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MJokNNForrVoctQ.geometry}
          material={materials.uhSjoqjjxLxIJEp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.uHvofqgpMqlssnA.geometry}
          material={materials.lMzofmcJBoknbil}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dmvkHjlAcBilttn.geometry}
          material={materials.lMzofmcJBoknbil}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.UtxqCQdxFKUWTRG.geometry}
          material={materials.JMJEizFSpcnBLBu}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.iQgbGlzLYxmnkEJ.geometry}
          material={materials.lMzofmcJBoknbil}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LucfwAzaOiBHGBs.geometry}
          material={materials.MyWTkmNpPcgwehb}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tJsALhsZGYXQBFg.geometry}
          material={materials.IyRtefachzKUcBb}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.vjEAQNHpUyNbGVA.geometry}
          material={materials.dULQkYmOHsuNGwk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.iFNIuSzIVSntlTY.geometry}
          material={materials.kgpBHanvuTGSAYr}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.IsQUyjZKDNlKKvu.geometry}
          material={materials.qDOcIjVpElQVnfu}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RFwGWThZbNKmLgt.geometry}
          material={materials.gMuXNdoZqzJLAvR}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lWAKZCzBqgMknbU.geometry}
          material={materials.IyRtefachzKUcBb}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.VykuVRzGucARcnD.geometry}
          material={materials.lMzofmcJBoknbil}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.jNQJlphSrIRrBKf.geometry}
          material={materials.JMJEizFSpcnBLBu}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XXvXucwLAbdmpHX.geometry}
          material={materials.lMzofmcJBoknbil}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.aXNMDmcsLKgffRv.geometry}
          material={materials.MyWTkmNpPcgwehb}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.nWGkHaZOXZFJZKv.geometry}
          material={materials.dULQkYmOHsuNGwk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pOJkkptsLytmtVv.geometry}
          material={materials.kgpBHanvuTGSAYr}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.xyVfpiYtqUaEsxm.geometry}
          material={materials.qDOcIjVpElQVnfu}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bPmBAuLIgCpxfIo.geometry}
          material={materials.ILBWplikIEjpQFu}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GkNcoDHRYmNOzNo.geometry}
          material={materials.ILBWplikIEjpQFu}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XRIeMaUGHSkJQqD.geometry}
          material={materials.JEqrlnZSfFxzXyR}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BOsOutQtwlhQDkr.geometry}
          material={materials.axobLmsfiYAnCsP}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.jrDatUzPyHNlXIy.geometry}
          material={materials.ANqxLmGmmZDkKZr}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.yaqXFfePSuyasqv.geometry}
          material={materials.JFsLNaKevrqxAHS}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tyXDSqxGNFRcIOf.geometry}
          material={materials.JFsLNaKevrqxAHS}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TQYwHoYhoHtCqfY.geometry}
          material={materials.JkJKKnxTIntgQHC}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.KGTPsmZXiKwUxBA.geometry}
          material={materials.JFsLNaKevrqxAHS}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rFfmCkJAIfvvcoV.geometry}
          material={materials.JkJKKnxTIntgQHC}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.kfFsvEDJevOTjOb.geometry}
          material={materials.CLxgtuDKMkHlfIs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.qjsWGaEQfNknQeo.geometry}
          material={materials.wHLUdvjLSAdAzpD}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mgkXJLMmHQwAPUS.geometry}
          material={materials.QTWCiCCGMSxWgbc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sFjRDkvMUTeoufu.geometry}
          material={materials.EgczyvedEqzqMFX}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GTNgXHvClILzWkZ.geometry}
          material={materials.wHLUdvjLSAdAzpD}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.VJHFxSHDwMHWYbD.geometry}
          material={materials.JFsLNaKevrqxAHS}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NFMjtFHlCmDDDye.geometry}
          material={materials.fwZBQTUFaZPSpvr}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HvmhNBkcFNCkETn.geometry}
          material={materials.fwZBQTUFaZPSpvr}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ljQqiMAOjJnstlz.geometry}
          material={materials.fwZBQTUFaZPSpvr}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.UfCFTvPHobNYNuw.geometry}
          material={materials.fwZBQTUFaZPSpvr}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RCtkcivgrajBiil.geometry}
          material={materials.gSPFLmkAjqDsDpN}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FtUZpgMrQeBuRwX.geometry}
          material={materials.JFsLNaKevrqxAHS}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CjrSGiCPDxNIlLL.geometry}
          material={materials.fwZBQTUFaZPSpvr}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cSSDqdAfWghogrf.geometry}
          material={materials.TOXCTGGcpkubhJV}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wAlSALURSIywUpI.geometry}
          material={materials.fwZBQTUFaZPSpvr}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.huiqOZNSnkdxFNi.geometry}
          material={materials.hOQFVPUkStlnLZL}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MlrGbWjzMhpBLgs.geometry}
          material={materials.JFsLNaKevrqxAHS}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.nZNcztTHfduCKSt.geometry}
          material={materials.rtSfIyWixTDVpUY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lEnYifWpSCJrErk.geometry}
          material={materials.pQhxnNuPXoHfCWe}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.izLdmgMAtFNCERj.geometry}
          material={materials.bxAqWBgABbIjzMY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cSEmYvJalQNIQhs.geometry}
          material={materials.jsQvjteHecACAeR}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.YbRoDtvjJInZyJV.geometry}
          material={materials.pQhxnNuPXoHfCWe}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.jWuDbHTaFBaDrrZ.geometry}
          material={materials.bxAqWBgABbIjzMY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FjuCyHASTTcZWMa.geometry}
          material={materials.jsQvjteHecACAeR}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XWpivUINjhZkYcr.geometry}
          material={materials.QTWCiCCGMSxWgbc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ZfIqyVMdJBwdcCh.geometry}
          material={materials.QTWCiCCGMSxWgbc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QWWffXFZwcUtXBq.geometry}
          material={materials.EgczyvedEqzqMFX}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.nFJQEQmmoUGBnDJ.geometry}
          material={materials.JFsLNaKevrqxAHS}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.urVwmigsGssgzve.geometry}
          material={materials.JFsLNaKevrqxAHS}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dxoUetmUtIBIVWe.geometry}
          material={materials.QTWCiCCGMSxWgbc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.giroUgjRKWjGLZl.geometry}
          material={materials.EgczyvedEqzqMFX}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tCtMfEJwdLuvQGF.geometry}
          material={materials.KEnlbNmQcpvdozb}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.yAsoSSImdAWHEeb.geometry}
          material={materials.KEnlbNmQcpvdozb}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.esWBIEGuqiSJTxI.geometry}
          material={materials.KEnlbNmQcpvdozb}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AoltIyCMGTXxbug.geometry}
          material={materials.KEnlbNmQcpvdozb}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dXHoHaAUioufqIg.geometry}
          material={materials.ZwfmonZpLDaDbGy}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SlAbfqkVZCCQOaf.geometry}
          material={materials.ZwfmonZpLDaDbGy}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.qczdsxpvVWujaAs.geometry}
          material={materials.ZwfmonZpLDaDbGy}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HBgvryqiUSEQVsz.geometry}
          material={materials.ZwfmonZpLDaDbGy}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RVbVFOYkEoTWZJR.geometry}
          material={materials.lciUnRZYuzqSpWr}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LqHGbWICfVuDiVa.geometry}
          material={materials.dvmeoUrdxtrSUKH}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evAvupWGSpKoduy.geometry}
          material={materials.KEnlbNmQcpvdozb}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tfoIbGUlplBnnGI.geometry}
          material={materials.KEnlbNmQcpvdozb}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.KbIuewYygqAXAOJ.geometry}
          material={materials.KEnlbNmQcpvdozb}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.STnvEOzUJTbYYoX.geometry}
          material={materials.KEnlbNmQcpvdozb}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pVZQtUhwcfzpspL.geometry}
          material={materials.ZwfmonZpLDaDbGy}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ISzOYZOQvVfmQYC.geometry}
          material={materials.ZwfmonZpLDaDbGy}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.yPLdQhxBlbsTdLZ.geometry}
          material={materials.ZwfmonZpLDaDbGy}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.KsxOHCkvAaPsioP.geometry}
          material={materials.ZwfmonZpLDaDbGy}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GZLqLapefOYGUhv.geometry}
          material={materials.lciUnRZYuzqSpWr}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.zVTeycOoDBbsgsY.geometry}
          material={materials.dvmeoUrdxtrSUKH}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NzfkbcPdvgFzApF.geometry}
          material={materials.KEnlbNmQcpvdozb}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WnfDwdqJiyacwNu.geometry}
          material={materials.JFsLNaKevrqxAHS}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ulUHXepohBRrBai.geometry}
          material={materials.fmmGyvGJVnVViXe}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bvBVGjqyifVGqeO.geometry}
          material={materials.OthgPpktWeqGgKp}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/apple_vision_pro_ios16.glb');
